- type: playTimeTracker
  id: JobLeaderArrows

- type: playTimeTracker
  id: JobSoldierArrows

- type: playTimeTracker
  id: JobSoldierCCA

- type: playTimeTracker
  id: JobSoldierOTA

- type: playTimeTracker
  id: JobSoldierCCAC

- type: playTimeTracker
  id: JobCentCommInspector

- type: playTimeTracker
  id: JobCentCommChiefOfStaff

- type: playTimeTracker
  id: JobCentCommIntern

- type: playTimeTracker
  id: JobCentCommIDOperator

- type: playTimeTracker
  id: JobCentCommSpecOpsOperator
