- type: playTimeTracker
  id: JobLeaderArrows

- type: playTimeTracker
  id: JobSoldierArrows

- type: playTimeTracker
  id: JobSoldierCCA

- type: playTimeTracker
  id: JobSoldierOTA

- type: playTimeTracker
  id: JobSoldierCCAC

- type: playTimeTracker
  id: JobLustCentCommInspector

- type: playTimeTracker
  id: JobLustCentCommChiefOfStaff

- type: playTimeTracker
  id: JobLustCentCommIntern

- type: playTimeTracker
  id: JobLustCentCommIDOperator

- type: playTimeTracker
  id: JobLustCentCommSpecOpsOperator

- type: playTimeTracker
  id: JobLustCentCommMaid
