- type: job
  id: CentCommOperator
  name: job-name-centcomop
  description: job-description-centcomop
  playTimeTracker: JobCentCommOperator
  requirements:
  - !type:DiscordRoleRequirement
  # Lust-Start
  - !type:OverallPlaytimeRequirement
    time: 10h
#  - !type:DepartmentTimeRequirement
#    department: Command
#    time: 10h
#  - !type:DepartmentTimeRequirement
#    department: Law
#    time: 10h
#  - !type:RoleTimeRequirement
#    role: JobLustCentCommIntern
#    time: 12h
  # Lust-End
  weight: 50 # Lust-Edit
  setPreference: true
  startingGear: CentCommOperatorGearQillu # Lust-Edit
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  radioBold: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  # Lust-Start
  - !type:AddComponentSpecial
    components:
    - type: ParadoxCloneImmune
  # Lust-End


- type: startingGear
  id: CentCommOperatorGear
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomOperatorPDA
    ears: ClothingHeadsetCentCom
    belt: WeaponPistolN1984
  storage:
    back:
    - RubberStampCentcom

- type: chameleonOutfit
  id: CentCommOperatorChameleonOutfit
  job: CentCommOperator
